
%macro calculateSampleSize();
data _temp;
%if &adapt=power %then %do;
  do power=&power_l to &power_u by &power_inc;
    _p0=&_p0; _p1=&_p1; n=&n; k=&k;
	output;
  end;
%end;
%else %if &adapt=p1 %then %do;
  %let _p1_l=&p1_l/1000;
  %let _p1_u=&p1_u/1000;
  %let _p1_inc=&p1_inc/1000;
  do _p1=&_p1_l to &_p1_u by &_p1_inc;
    power=&power; _p0=&_p0; n=&n; k=&k;
	output;
  end;
%end;
%else %if &adapt=n %then %do;
  do n=&n_l to &n_u by &n_inc;
    power=&power; _p0=&_p0; _p1=&_p1; k=&k;
	output;
  end;
%end;
%else %if &adapt=k %then %do;
  do k=&k_l to &k_u by &k_inc;
    power=&power; _p0=&_p0; _p1=&_p1; n=&n;
	output;
  end;
%end;
%else %do;
  power=&power; _p0=&_p0; _p1=&_p1; n=&n; k=&k;
%end;
data &dset;
  set _temp;
  alpha=&alpha;
  alpha_comp=&alpha_comp;
  beta=1-power;
  zAlpha=-probit((alpha/(alpha_comp*2)));
  zBeta=-probit(beta);
  a=(zAlpha+zBeta)**2;
  b=(_p0*(1-_p0))/n;
  c=(_p1*(1-_p1))/n;
  d=(k**2)*((_p0**2)+(_p1**2));
  e=(_p0-_p1)**2;
  f=1+((a*(b+c+d))/e);
  clusters=1+ceil((a*(b+c+d))/e);
run;
%mend;
